[[main]]
    name = "Solutions & Services"
    url = "/solutions-services"
    weight = 10
[[main]]
    parent = "Solutions & Services"
    name = "Private Cloud"
    url = "/private-cloud"
    weight = 11
[[main]]
    parent = "Solutions & Services"
    name = "Distributed Storage"
    url = "/distributed-storage"
    weight = 12
[[main]]
    parent = "Solutions & Services"
    name = "Migration Service"
    url = "/migration-service"
    weight = 13
[[main]]
    parent = "Solutions & Services"
    name = "Public Cloud"
    url = "/public-cloud"
    weight = 14
[[main]]
    parent = "Solutions & Services"
    name = "Automation"
    url = "/automation"
    weight = 15
[[main]]
    name = "Products"
    url = "/products"
    weight = 20
[[main]]
    parent = "Products"
    name = "Cloud Management Tools"
    url = "/cloud-management-tools"
    weight = 21
[[main]]
    parent = "Products"
    name = "Automation Platforms"
    url = "/automation-platforms"
    weight = 22
[[main]]
    parent = "Products"
    name = "Monitoring Solutions"
    url = "/monitoring-solutions"
    weight = 23
[[main]]
    name = "About"
    url = "/about"
    weight = 30
[[main]]
    name = "Contact Us"
    url = "/contact"
    weight = 40
