baseURL = "https://nubestack.com/"
languageCode = "en-us"
#title = "Arcana for Hugo"
theme = "hugo-arcana"
copyright = "© NubeStack. All rights reserved"

# Menu Configuration - Easy to manage menu order and items
[menu]
[[menu.main]]
name = "Services"
url = "#"
weight = 1

[[menu.main]]
name = "Cloud Solutions"
url = "/services/cloud"
parent = "Services"
weight = 11

[[menu.main]]
name = "Web Development"
url = "/services/web-development"
parent = "Services"
weight = 12

[[menu.main]]
name = "DevOps"
url = "/services/devops"
parent = "Services"
weight = 13

[[menu.main]]
name = "Consulting"
url = "/services/consulting"
parent = "Services"
weight = 14

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = false

   [[params.social]]
        title = "WhatsApp"
        icon = "fa-whatsapp"
        url = "https://www.linkedin.com/company/nubestack"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/company/nubestack"


    [params.footer]

        [[params.footer.links]]
            header = "Links to Stuff"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"

        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"

        [[params.footer.links]]
            header = "Additional Resources"
        [[params.footer.links.links]]
            title = "Cloud Migration Guide"
            url = "#"
        [[params.footer.links.links]]
            title = "DevOps Best Practices"
            url = "#"
        [[params.footer.links.links]]
            title = "Security Compliance"
            url = "#"
        [[params.footer.links.links]]
            title = "Technology Roadmap"
            url = "#"

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
