baseURL = "https://nubestack.com"
languageCode = "en-us"
#title = "Arcana for Hugo"
theme = "hugo-arcana"
copyright = "© NubeStack. All rights reserved"

# Menu Configuration - Easy to manage menu order and items
[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 40

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    images = ['images/metaimage.jpg']
    show_post_dates = false

   [[params.social]]
        title = "WhatsApp"
        icon = "fa-whatsapp"
        url = "https://www.linkedin.com/company/nubestack"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/company/nubestack"


    [params.footer]

        [[params.footer.links]]
            header = "Links to Stuff"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"

        [[params.footer.links]]
            header = "More Links to Stuff"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"


        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
