baseURL = "https://ahmadfsbd.github.io/nubestack/"
languageCode = "en-us"
title = "NuBestack Cloud Services"
theme = "hugo-arcana"
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[params]
  description = "Scalable cloud infrastructure and DevOps solutions."
  author = "NuBestack Team"
  favicon = "img/favicon.ico"     # place under /static/img/
